format_version: 2
pipelines:
  java-ci-demo-yml:
    group: defaultGroup
    materials:
      backend: 
        git: https://github.com/danodic/java-ci-demo-app.git
        branch: main
    stages:
      - test:
          clean_workspace: true
          jobs:
            unit-test:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                      - clean
                      - compile
                      - test
      - deploy:
          jobs:
            package:
              artifacts:
               - build:
                   source: target/
                   destination: build
               - test:
                   source: target/surefire-reports/
                   destination: test
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                      - package
