format_version: 2
pipelines:
  java-ci-demo-yml:
    group: defaultGroup
    materials:
      backend: 
        git: https://github.com/danodic/java-ci-demo-app.git
        branch: main
    stages:
      - test:
          clean_workspace: true
          jobs:
            unit-test:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                      - clean
                      - compile
                      - test
      - package:
          clean_workspace: true
          jobs:
            unit-test:
              tasks:
                - exec:
                    run_if: passed
                    command: mvn
                    arguments:
                      - package
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: scp
                    arguments:
                      - target/ci-demo.jar
                      - ci@192.168.56.107:/home/ci/gocd
